# Generate C:\Users\<you>\.wslconfig, sized for THIS machine.
# Idempotent - safe to re-run.
#
#     .\write-wslconfig.ps1
#
# ASCII only. Windows PowerShell 5.1 reads .ps1 as ANSI without a BOM.
#
# Generated rather than committed: a fixed memory figure that suits one machine
# starves another. config.json can pin the numbers if you want them fixed.

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'lib\config.ps1')

$cfg = Get-SetupConfig

$totalGB = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB)
$cpus    = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors

# Leave Windows room to work. All distros share this one budget: they run in a
# single utility VM, so this is the total across every zone, not per zone.
$memGB = if ($cfg.wsl.memoryGB) { [int]$cfg.wsl.memoryGB } else { [math]::Max(4, [math]::Floor($totalGB * 0.6)) }
$procs = if ($cfg.wsl.processors) { [int]$cfg.wsl.processors } else { [math]::Max(2, $cpus - 2) }
$swap  = if ($cfg.wsl.swapGB -ne $null) { [int]$cfg.wsl.swapGB } else { 8 }

Write-Host "detected: $totalGB GB RAM, $cpus logical CPUs"
Write-Host "using:    memory=${memGB}GB processors=$procs swap=${swap}GB"

$content = @"
# GENERATED by hosts/windows/write-wslconfig.ps1 - edit config.json, not this file.
#
# GLOBAL settings for the WSL2 utility VM. Applies to every distro.
# Per-distro settings live in /etc/wsl.conf - see zones/wsl.conf.template.
#
# Detected $totalGB GB RAM / $cpus logical CPUs.
# Apply changes with:  wsl --shutdown

[wsl2]
memory=${memGB}GB
processors=$procs
swap=${swap}GB

# See decisions/0003-networking-mode.md. NAT is the conservative choice; note
# that zones share one network namespace either way, so this only decides
# whether the Windows host's loopback joins them too.
networkingMode=nat
localhostForwarding=true
firewall=true
dnsTunneling=true
autoProxy=true

# Docker inside a distro does NOT need this. Needed only for KVM, Android
# emulators, or VMs inside WSL. Symptom if you need it: "KVM is not available".
nestedVirtualization=false

vmIdleTimeout=60000

[experimental]
autoMemoryReclaim=gradual

# sparseVhd is deliberately absent. WSL currently refuses it:
#   "Sparse VHD support is currently disabled due to potential data corruption."
# The only route is --set-sparse true --allow-unsafe, which is not worth taking.
# Reclaim space manually with diskpart instead - see decisions/0014.
"@

$dest = "C:\Users\$($cfg.windowsUser)\.wslconfig"
if ((Test-Path $dest) -and -not (Get-Content $dest -Raw).StartsWith('# GENERATED')) {
    Copy-Item $dest "$dest.bak" -Force
    Write-Warning "backed up your existing .wslconfig to $dest.bak"
}
Set-Content -Path $dest -Value $content -Encoding ASCII
Write-Host "wrote $dest"
Write-Host ""
Write-Host "Run 'wsl --shutdown' to apply."
